Repository nandium/RouteMaker, pull requests merged in 2021-04, with the labels that each got.

#2 Feature/User-Interface
  user_interface/.eslintrc.js
  user_interface/.gitignore
  user_interface/README.md
  user_interface/babel.config.js
  user_interface/package-lock.json
  user_interface/package.json
  user_interface/public/favicon.ico
  user_interface/public/index.html
  user_interface/src/App.vue
  user_interface/src/api/getBoundingBox.js
  user_interface/src/assets/logo.png
  user_interface/src/components/ImageUploader.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/main.js
  user_interface/src/router/index.js
  user_interface/src/scripts/BootstrapScript.js
  user_interface/src/store/index.js
  user_interface/src/store/modules/home.js
  user_interface/src/views/About.vue
  user_interface/src/views/Home.vue
Labels: feature

#3 Feature/canvas
  user_interface/package-lock.json
  user_interface/package.json
  user_interface/src/App.vue
  user_interface/src/common/getBoundingBox.js
  user_interface/src/common/utils.js
  user_interface/src/components/ImageUploader.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/main.js
  user_interface/src/scripts/KonvaScript.js
  user_interface/src/store/modules/home.js
  user_interface/src/views/Home.vue
Labels: feature

#4 Feature/bounding box
  local_prediction/test_images/Screenshot_4.jpg
  user_interface/src/common/getBoundingBox.js
  user_interface/src/common/selectModes.js
  user_interface/src/common/utils.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ImageUploader.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/components/ModeSelector.vue
  user_interface/src/store/modules/home.js
  user_interface/src/views/About.vue
  user_interface/src/views/Home.vue
Labels: feature

#5 Docs/readme
  README.md
  docs/Screenshot_1.jpg
  docs/Screenshot_2.jpg
  docs/Screenshot_3.jpg
Labels: documentation

#6 Feature/mode selector update
  README.md
  docs/Screenshot_1.jpg
  docs/Screenshot_2.jpg
  docs/Screenshot_3.jpg
  docs/Screenshot_4.jpg
  docs/Screenshot_5.jpg
  user_interface/package-lock.json
  user_interface/package.json
  user_interface/src/assets/Screenshot_1.jpg
  user_interface/src/assets/Screenshot_2.jpg
  user_interface/src/assets/Screenshot_3.jpg
  user_interface/src/assets/Screenshot_4.jpg
  user_interface/src/assets/Screenshot_5.jpg
  user_interface/src/common/selectModes.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/components/Loader.vue
  user_interface/src/components/ModeSelector.vue
  user_interface/src/store/modules/home.js
  user_interface/src/views/About.vue
Labels: feature

#15 Feature/add-pinch-zoom-and-optimize-konva
  user_interface/src/common/konvaMethods.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/scripts/KonvaScript.js
  user_interface/src/views/Home.vue
Labels: feature

#18 Fix/pinch zoom lag and other issues
  user_interface/src/common/konvaMethods.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ImageUploader.vue
  user_interface/src/components/ModeSelector.vue
Labels: bug

#19 Feature/Enhance Nav Bar
  user_interface/src/App.vue
  user_interface/src/components/NavBar.vue
  user_interface/src/router/index.js
  user_interface/src/store/index.js
  user_interface/src/store/modules/app.js
Labels: enhancement

#21 Feature/Restrict image scaling
  user_interface/package-lock.json
  user_interface/package.json
  user_interface/src/common/konvaMethods.js
  user_interface/src/components/ImageViewer.vue
Labels: enhancement

#23 Feature/Manual Bounding Boxes
  docs/Screenshot_1.jpg
  docs/Screenshot_2.jpg
  docs/Screenshot_3.jpg
  docs/Screenshot_4.jpg
  docs/Screenshot_5.jpg
  user_interface/src/assets/Screenshot_1.jpg
  user_interface/src/assets/Screenshot_2.jpg
  user_interface/src/assets/Screenshot_3.jpg
  user_interface/src/assets/Screenshot_4.jpg
  user_interface/src/assets/Screenshot_5.jpg
  user_interface/src/common/api/getBoundingBox.js
  user_interface/src/common/boundingBoxAttributes.js
  user_interface/src/common/enumBoxClass.js
  user_interface/src/common/enumSelectModes.js
  user_interface/src/common/getBoundingBox.js
  user_interface/src/common/konva/drawLayer.js
  user_interface/src/common/konva/index.js
  user_interface/src/common/konva/listeners.js
  user_interface/src/common/konva/utils.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ImageUploader.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/components/ModeSelector.vue
  user_interface/src/store/modules/home.js
Labels: feature

#24 Feature/enhance draw box function
  user_interface/src/common/boundingBoxAttributes.js
  user_interface/src/common/konva/drawLayer.js
  user_interface/src/components/ImageViewer.vue
  user_interface/src/components/ModeSelector.vue
  user_interface/src/store/modules/home.js
Labels: enhancement

#28 fix: Add image compression
  user_interface/package-lock.json
  user_interface/package.json
  user_interface/src/components/ImageUploader.vue
Labels: bug

#32 Feature/add start end holds
  user_interface/src/common/enumBoxClass.js
  user_interface/src/common/enumHandStartMode.js
  user_interface/src/common/enumSelectMode.js
  user_interface/src/common/konva/drawLayer.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ImageViewer.vue
  user_interface/src/components/ModeSelector.vue
  user_interface/src/store/modules/home.js
Labels: feature

#39 Feature/Add white borders to numbering
  user_interface/src/common/boundingBoxAttributes.js
  user_interface/src/components/BoundingBox.vue
Labels: enhancement

#40 Feature/Add google analytics tracking
  user_interface/package-lock.json
  user_interface/public/index.html
  user_interface/vue.config.js
Labels: feature

#42 Feature/Separate backend to dev and prod
  lambda_backend/handler.py
  lambda_backend/requirements.txt
  lambda_backend/serverless.yml
  lambda_backend/utils.py
  package.json
Labels: feature

#43 Fix/Hold switching
  user_interface/src/common/enumBoxMode.js
  user_interface/src/components/BoundingBox.vue
  user_interface/src/components/ModeSelector.vue
Labels: bug

#45 Chore/setup linter
  .eslintrc.js
  .github/workflows/lint.yml
  README.md
  package-lock.json
  package.json
  user_interface/src/components/ImageUploader.vue
Labels: enhancement
