Repository nandium/RouteMaker, pull requests merged in 2021-06, with the labels that each got.

#66 Feature/Gym Request Endpoint
  docs/API Documentation Draft.pdf
  docs/API Documentation V1.1.0.pdf
  lambda_backend/.gitignore
  lambda_backend/cognito_setup/serverless.yml
  lambda_backend/database_setup/serverless.yml
  lambda_backend/package-lock.json
  lambda_backend/postman_collections/Bouldering - Route.postman_collection.json
  lambda_backend/postman_collections/Bouldering - User.postman_collection.json
  lambda_backend/predict_microservice/serverless.yml
  lambda_backend/route_microservice/serverless.yml
  lambda_backend/route_microservice/src/common/cognito.ts
  lambda_backend/route_microservice/src/common/index.ts
  lambda_backend/route_microservice/src/common/schema.ts
  lambda_backend/route_microservice/src/common/types.ts
  lambda_backend/route_microservice/src/createRoute.ts
  lambda_backend/route_microservice/src/getAllGyms.ts
  lambda_backend/route_microservice/src/getRouteDetails.ts
  lambda_backend/route_microservice/src/requestGym.ts
  lambda_backend/route_microservice/src/upVoteRoute.ts
  lambda_backend/s3_bucket_setup/serverless.yml
  lambda_backend/serverless-deploy.sh
  lambda_backend/sns_setup/package-lock.json
  lambda_backend/sns_setup/package.json
  lambda_backend/sns_setup/serverless.yml
  lambda_backend/sns_setup/src/telegramDispatcher.ts
  lambda_backend/sns_setup/tsconfig.json
  lambda_backend/user_microservice/serverless.yml
  lambda_backend/user_microservice/src/confirmSignup.ts
  lambda_backend/user_microservice/src/login.ts
  lambda_backend/user_microservice/src/signup.ts
  package.json
Labels: bug, feature

#70 Feature/Add CD frontend
  .github/workflows/deploy.yml
  ionic_user_interface/src/components/wall-image-viewer/getBoundingBoxes.ts
Labels: enhancement

#71 Feat/delete user endpoint
  docs/API Documentation V1.1.0.pdf
  docs/API Documentation V1.1.1.pdf
  lambda_backend/postman_collections/Bouldering - User.postman_collection.json
  lambda_backend/user_microservice/serverless.yml
  lambda_backend/user_microservice/src/common/types.ts
  lambda_backend/user_microservice/src/deleteUser.ts
  lambda_backend/user_microservice/src/logout.ts
Labels: feature

#79 Fix/Ensure deployed environ parses image the same way
  lambda_backend/predict_microservice/requirements.txt
  lambda_backend/predict_microservice/utils.py
  model_training/local_prediction/Pipfile
  model_training/local_prediction/Pipfile.lock
Labels: bug

#65 Feat/Add login page
  ionic_user_interface/package-lock.json
  ionic_user_interface/package.json
  ionic_user_interface/src/components/ErrorMessage.vue
  ionic_user_interface/src/components/header/Header.vue
  ionic_user_interface/src/components/header/LoginButton.vue
  ionic_user_interface/src/main.ts
  ionic_user_interface/src/providers.ts
  ionic_user_interface/src/router/index.ts
  ionic_user_interface/src/views/About.vue
  ionic_user_interface/src/views/Confirm.vue
  ionic_user_interface/src/views/Home.vue
  ionic_user_interface/src/views/Login.vue
  ionic_user_interface/src/views/Profile.vue
  ionic_user_interface/src/views/Signup.vue
  ionic_user_interface/tsconfig.json
  package-lock.json
  vetur.config.js
Labels: feature

#78 Docs/Improve API documentation
  .github/workflows/swagger.yml
  docs/API Documentation V1.1.2.pdf
  docs/README.md
  docs/swagger-1.2.json
Labels: documentation

#72 Feat/Add gym selection page
  ionic_user_interface/package-lock.json
  ionic_user_interface/package.json
  ionic_user_interface/src/common/api/route/config.ts
  ionic_user_interface/src/common/api/route/getGyms.ts
  ionic_user_interface/src/components/gym-selector/AutoComplete.vue
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/composables/useCanvasWidth.ts
  ionic_user_interface/src/providers.ts
  ionic_user_interface/src/router/index.ts
  ionic_user_interface/src/views/Gyms.vue
  ionic_user_interface/src/views/Home.vue
Labels: feature

#85 Feat/change delete endpoint params
  docs/swagger-1.2.json
  docs/swagger-1.3.json
  lambda_backend/postman_collections/Bouldering - Route.postman_collection.json
  lambda_backend/route_microservice/src/common/schema.ts
  lambda_backend/route_microservice/src/common/types.ts
  lambda_backend/route_microservice/src/deleteComment.ts
  lambda_backend/route_microservice/src/deleteRoute.ts
Labels: enhancement

#84 Feat/improve login
  ionic_user_interface/.eslintrc.js
  ionic_user_interface/package-lock.json
  ionic_user_interface/src/App.vue
  ionic_user_interface/src/components/MessageBox.vue
  ionic_user_interface/src/components/gym-selector/GymRequestForm.vue
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/components/header/LoginButton.vue
  ionic_user_interface/src/providers.ts
  ionic_user_interface/src/theme/variables.css
  ionic_user_interface/src/views/About.vue
  ionic_user_interface/src/views/Confirm.vue
  ionic_user_interface/src/views/Gyms.vue
  ionic_user_interface/src/views/Home.vue
  ionic_user_interface/src/views/Login.vue
  ionic_user_interface/src/views/Profile.vue
  ionic_user_interface/src/views/RequestGym.vue
  ionic_user_interface/src/views/Signup.vue
  package-lock.json
Labels: feature

#102 Feat/Auth improvement UI
  README.md
  docs/swagger-1.7.json
  ionic_user_interface/src/App.vue
  ionic_user_interface/src/components/gym-selector/GymRequestForm.vue
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/providers.ts
  ionic_user_interface/src/router/index.ts
  ionic_user_interface/src/views/Confirm.vue
  ionic_user_interface/src/views/ForgotPassword.vue
  ionic_user_interface/src/views/Login.vue
  ionic_user_interface/src/views/ResetPassword.vue
  ionic_user_interface/src/views/Signup.vue
  lambda_backend/user_microservice/src/forgotPassword.ts
Labels: enhancement

#104 Feat/backend user compliance
  docs/swagger-1.8.json
  lambda_backend/cognito_setup/serverless.yml
  lambda_backend/database_setup/serverless.yml
  lambda_backend/postman_collections/Bouldering - Route.postman_collection.json
  lambda_backend/postman_collections/Bouldering - User.postman_collection.json
  lambda_backend/route_microservice/package-lock.json
  lambda_backend/route_microservice/package.json
  lambda_backend/route_microservice/serverless.yml
  lambda_backend/route_microservice/src/addComment.ts
  lambda_backend/route_microservice/src/common/badwords.ts
  lambda_backend/route_microservice/src/common/cognito.ts
  lambda_backend/route_microservice/src/common/db.ts
  lambda_backend/route_microservice/src/common/index.ts
  lambda_backend/route_microservice/src/common/schema.ts
  lambda_backend/route_microservice/src/common/types.ts
  lambda_backend/route_microservice/src/config.ts
  lambda_backend/route_microservice/src/createRoute.ts
  lambda_backend/route_microservice/src/deleteComment.ts
  lambda_backend/route_microservice/src/deleteRoute.ts
  lambda_backend/route_microservice/src/getAllGyms.ts
  lambda_backend/route_microservice/src/getRouteDetails.ts
  lambda_backend/route_microservice/src/getRoutesByGym.ts
  lambda_backend/route_microservice/src/gradeRoute.ts
  lambda_backend/route_microservice/src/reportRoute.ts
  lambda_backend/route_microservice/src/requestGym.ts
  lambda_backend/route_microservice/src/upVoteRoute.ts
  lambda_backend/user_microservice/package-lock.json
  lambda_backend/user_microservice/package.json
  lambda_backend/user_microservice/serverless.yml
  lambda_backend/user_microservice/src/common/identityProvider.ts
  lambda_backend/user_microservice/src/common/index.ts
  lambda_backend/user_microservice/src/common/schema.ts
  lambda_backend/user_microservice/src/common/types.ts
  lambda_backend/user_microservice/src/confirmForgotPassword.ts
  lambda_backend/user_microservice/src/confirmSignup.ts
  lambda_backend/user_microservice/src/deleteUser.ts
  lambda_backend/user_microservice/src/disableUser.ts
  lambda_backend/user_microservice/src/enableAdmin.ts
  lambda_backend/user_microservice/src/forgotPassword.ts
  lambda_backend/user_microservice/src/login.ts
  lambda_backend/user_microservice/src/logout.ts
  lambda_backend/user_microservice/src/refreshToken.ts
  lambda_backend/user_microservice/src/reportUser.ts
  lambda_backend/user_microservice/src/resendCode.ts
  lambda_backend/user_microservice/src/signup.ts
Labels: enhancement

#108 Feat/routes by user
  docs/swagger-1.9.json
  lambda_backend/database_setup/serverless.yml
  lambda_backend/package-lock.json
  lambda_backend/package.json
  lambda_backend/postman_collections/Bouldering - Route.postman_collection.json
  lambda_backend/route_microservice/package-lock.json
  lambda_backend/route_microservice/serverless.yml
  lambda_backend/route_microservice/src/common/s3/index.ts
  lambda_backend/route_microservice/src/common/s3/s3.ts
  lambda_backend/route_microservice/src/common/s3/utils.ts
  lambda_backend/route_microservice/src/common/schema.ts
  lambda_backend/route_microservice/src/common/types.ts
  lambda_backend/route_microservice/src/createRoute.ts
  lambda_backend/route_microservice/src/deleteRoute.ts
  lambda_backend/route_microservice/src/getRouteDetails.ts
  lambda_backend/route_microservice/src/getRoutesByGym.ts
  lambda_backend/route_microservice/src/getRoutesByUser.ts
  lambda_backend/user_microservice/package-lock.json
  lambda_backend/user_microservice/src/common/schema.ts
Labels: feature

#111 Feat/toggle upvote
  README.md
  docs/swagger-1.10.json
  ionic_user_interface/.eslintrc
  ionic_user_interface/.eslintrc.js
  ionic_user_interface/src/common/api/route/getGymsByCountry.ts
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/views/UploadRoute.vue
  ionic_user_interface/tests/e2e/.eslintrc
  ionic_user_interface/tests/e2e/.eslintrc.js
  lambda_backend/postman_collections/Bouldering - Route.postman_collection.json
  lambda_backend/predict_microservice/utils.py
  lambda_backend/route_microservice/serverless.yml
  lambda_backend/route_microservice/src/common/schema.ts
  lambda_backend/route_microservice/src/common/types.ts
  lambda_backend/route_microservice/src/getAllGyms.ts
  lambda_backend/route_microservice/src/getGymsByCountry.ts
  lambda_backend/route_microservice/src/toggleUpvoteRoute.ts
  lambda_backend/route_microservice/src/upVoteRoute.ts
  lambda_backend/serverless-deploy.sh
Labels: enhancement
