Repository nandium/RouteMaker, pull requests merged in 2021-07, with the labels that each got.

#118 Fix/stuck canvas mobile
  ionic_user_interface/src/components/wall-image-viewer/Canvas.vue
  ionic_user_interface/src/components/wall-image-viewer/stageListeners.ts
  ionic_user_interface/src/views/Home.vue
Labels: bug

#121 Feat/Custom Logo
  README.md
  docs/favicon-lightmode-name.svg
  ionic_user_interface/public/assets/icons/android-chrome-192x192.png
  ionic_user_interface/public/assets/icons/android-chrome-512x512.png
  ionic_user_interface/public/assets/icons/apple-touch-icon.png
  ionic_user_interface/public/assets/icons/browserconfig.xml
  ionic_user_interface/public/assets/icons/favicon-16x16.png
  ionic_user_interface/public/assets/icons/favicon-32x32.png
  ionic_user_interface/public/assets/icons/favicon-darkmode-name.svg
  ionic_user_interface/public/assets/icons/favicon-lightmode-name.svg
  ionic_user_interface/public/assets/icons/favicon.ico
  ionic_user_interface/public/assets/icons/mstile-144x144.png
  ionic_user_interface/public/assets/icons/mstile-150x150.png
  ionic_user_interface/public/assets/icons/mstile-310x150.png
  ionic_user_interface/public/assets/icons/mstile-310x310.png
  ionic_user_interface/public/assets/icons/mstile-70x70.png
  ionic_user_interface/public/assets/icons/safari-pinned-tab.svg
  ionic_user_interface/public/index.html
  ionic_user_interface/src/components/header/Header.vue
Labels: enhancement

#123 Improve UX for canvas
  README.md
  docs/Screenshot_1.jpg
  docs/Screenshot_2.jpg
  docs/Screenshot_3.jpg
  docs/Screenshot_4.jpg
  docs/Screenshot_5.jpg
  docs/Screenshot_6.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_1.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_2.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_3.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_4.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_5.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_6.jpg
  ionic_user_interface/src/components/header/Header.vue
  ionic_user_interface/src/components/wall-image-viewer/Canvas.vue
  ionic_user_interface/src/components/wall-image-viewer/types.ts
  ionic_user_interface/src/views/About.vue
Labels: enhancement

#126 Feature/Add daily upload limit
  lambda_backend/route_microservice/src/config.ts
  lambda_backend/route_microservice/src/createRoute.ts
Labels: enhancement

#129 Feature/User routes page
  ionic_user_interface/public/assets/screenshots/Screenshot_4.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_5.jpg
  ionic_user_interface/src/common/reportUserAlert.ts
  ionic_user_interface/src/components/GymMap.vue
  ionic_user_interface/src/components/GymRouteList.vue
  ionic_user_interface/src/components/UserRouteList.vue
  ionic_user_interface/src/components/gym-selector/GymRequestForm.vue
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/components/header/LoginButton.vue
  ionic_user_interface/src/components/wall-image-viewer/Canvas.vue
  ionic_user_interface/src/providers.ts
  ionic_user_interface/src/router/index.ts
  ionic_user_interface/src/views/About.vue
  ionic_user_interface/src/views/Confirm.vue
  ionic_user_interface/src/views/Gyms.vue
  ionic_user_interface/src/views/Login.vue
  ionic_user_interface/src/views/Profile.vue
  ionic_user_interface/src/views/ResetPassword.vue
  ionic_user_interface/src/views/Signup.vue
  ionic_user_interface/src/views/UploadRoute.vue
  ionic_user_interface/src/views/UserRoutes.vue
  ionic_user_interface/src/views/ViewRoute.vue
Labels: feature

#130 Feat/Delete routes
  README.md
  ionic_user_interface/package-lock.json
  ionic_user_interface/src/App.vue
  ionic_user_interface/src/common/api/route/getGymsByCountry.ts
  ionic_user_interface/src/common/reportUserAlert.ts
  ionic_user_interface/src/components/GymRouteList.vue
  ionic_user_interface/src/components/UserRouteList.vue
  ionic_user_interface/src/components/gym-selector/AutoComplete.vue
  ionic_user_interface/src/components/gym-selector/GymRequestForm.vue
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/components/header/Header.vue
  ionic_user_interface/src/components/header/LoginButton.vue
  ionic_user_interface/src/components/wall-image-viewer/Canvas.vue
  ionic_user_interface/src/providers.ts
  ionic_user_interface/src/router/index.ts
  ionic_user_interface/src/theme/variables.css
  ionic_user_interface/src/views/Explore.vue
  ionic_user_interface/src/views/Help.vue
  ionic_user_interface/src/views/Login.vue
  ionic_user_interface/src/views/New.vue
  ionic_user_interface/src/views/Profile.vue
  ionic_user_interface/src/views/UserRoutes.vue
  ionic_user_interface/src/views/ViewRoute.vue
  ionic_user_interface/tests/unit/example.spec.ts
Labels: enhancement

#133 Feature/Polish after feedback
  docs/swagger-1.12.json
  ionic_user_interface/package-lock.json
  ionic_user_interface/package.json
  ionic_user_interface/public/assets/screenshots/Screenshot_1.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_2.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_3.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_4.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_5.jpg
  ionic_user_interface/src/common/api/route/config.ts
  ionic_user_interface/src/common/api/route/getGymsByCountry.ts
  ionic_user_interface/src/common/api/route/getRouteDetails.ts
  ionic_user_interface/src/common/api/route/getRoutesByGym.ts
  ionic_user_interface/src/common/api/route/getRoutesByUser.ts
  ionic_user_interface/src/common/api/route/requestGym.ts
  ionic_user_interface/src/common/shareSocial.ts
  ionic_user_interface/src/components/GymRouteList.vue
  ionic_user_interface/src/components/UserRouteList.vue
  ionic_user_interface/src/components/VoteButton.vue
  ionic_user_interface/src/components/gym-selector/GymRequestForm.vue
  ionic_user_interface/src/components/gym-selector/GymSelector.vue
  ionic_user_interface/src/components/wall-image-viewer/Canvas.vue
  ionic_user_interface/src/main.ts
  ionic_user_interface/src/views/Explore.vue
  ionic_user_interface/src/views/Help.vue
  ionic_user_interface/src/views/New.vue
  ionic_user_interface/src/views/Profile.vue
  ionic_user_interface/src/views/RequestGym.vue
  ionic_user_interface/src/views/Signup.vue
  ionic_user_interface/src/views/UploadRoute.vue
  ionic_user_interface/src/views/UserRoutes.vue
  ionic_user_interface/src/views/ViewRoute.vue
  lambda_backend/route_microservice/src/common/schema.ts
Labels: enhancement

#135 Optimize/Reduce route details API call
  ionic_user_interface/src/common/api/route/addCommentToRoute.ts
  ionic_user_interface/src/common/api/route/changeRouteGrade.ts
  ionic_user_interface/src/common/api/route/getRouteDetails.ts
  ionic_user_interface/src/components/UserRouteList.vue
  ionic_user_interface/src/views/ViewRoute.vue
Labels: enhancement

#138 Feature/Delete routes user delete
  ionic_user_interface/public/assets/screenshots/Screenshot_1.jpg
  ionic_user_interface/public/assets/screenshots/Screenshot_5.jpg
  lambda_backend/database_setup/serverless.yml
  lambda_backend/package-lock.json
  lambda_backend/package.json
  lambda_backend/route_microservice/serverless.yml
  lambda_backend/route_microservice/src/common/db.ts
  lambda_backend/route_microservice/src/deleteUserDispatcher.ts
  lambda_backend/route_microservice/src/getRoutesByGym.ts
  lambda_backend/route_microservice/src/getRoutesByUser.ts
  lambda_backend/sns_setup/serverless.yml
  lambda_backend/user_microservice/serverless.yml
  lambda_backend/user_microservice/src/deleteUser.ts
  lambda_backend/user_microservice/src/reportUser.ts
Labels: feature
